#cloud-config

package_update: true

packages:
  - docker.io
  - docker-compose-v2
  - git

runcmd:
  - systemctl enable --now docker
  - mkdir -p /opt/lamp
  - git clone https://github.com/gokmenhasan73-cmyk/opgave3-lamp-azure.git /opt/lamp
  - cd /opt/lamp && docker compose up -d --build